### ISSUE TITLE
Maybe a better name for this package instead of "buttplug"

### ISSUE THREAD

**Issue by buismaarten** [iggyvolz/buttplug-php#1]

**Comment by iggyvolz** [comment]
Hi - the package name comes from the [protocol which this package implements](https://buttplug-developer-guide.docs.buttplug.io/docs/spec).  I did do a cursory sweep of GitHub/Packagist terms and didn't find anything that might cause an issue.  If there is an issue from one of the two sources (although I imagine GitHub doesn't have an issue given [the numerous other libraries which follow this naming standard](https://github.com/orgs/buttplugio/repositories?language=&q=buttplug&sort=&type=all), I'm open to changing, but unless that is the case the name will remain.
